import { BibleVerse } from "@shared/schema";
import kjvStrongsData from './bible-kjv-strongs.json';

export type WordToken = {
  english: string;
  strongs?: string | string[];  // Support both single and multiple Strong's tags
  original?: string;
};

export type BibleVerseWithTokens = BibleVerse & {
  tokens?: WordToken[];
  translation?: string;
};

export type Translation = 'KJV' | 'ESV' | 'NASB';

// Sample verses with Strong's concordance data for demonstration
const kjvWithStrongsData: BibleVerseWithTokens[] = [
  {
    id: "john-1-1-kjv",
    book: "John",
    chapter: 1,
    verse: 1,
    text: "In the beginning was the Word, and the Word was with God, and the Word was God.",
    translation: "KJV",
    strongsNumbers: ["G1722", "G746", "G2258", "G3056", "G2532", "G3056", "G2258", "G4314", "G2316", "G2532", "G3056", "G2258", "G2316"],
    greek: "Ἐν ἀρχῇ ἦν ὁ λόγος καὶ ὁ λόγος ἦν πρὸς τὸν θεόν καὶ θεὸς ἦν ὁ λόγος",
    tokens: [
      { english: "In", strongs: "G1722", original: "Ἐν" },
      { english: "the", strongs: "G746", original: "" },
      { english: "beginning", strongs: "G746", original: "ἀρχῇ" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "the", strongs: "G3056", original: "ὁ" },
      { english: "Word,", strongs: "G3056", original: "λόγος" },
      { english: "and", strongs: "G2532", original: "καὶ" },
      { english: "the", strongs: "G3056", original: "ὁ" },
      { english: "Word", strongs: "G3056", original: "λόγος" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "with", strongs: "G4314", original: "πρὸς" },
      { english: "God,", strongs: "G2316", original: "θεόν" },
      { english: "and", strongs: "G2532", original: "καὶ" },
      { english: "the", strongs: "G3056", original: "" },
      { english: "Word", strongs: "G3056", original: "λόγος" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "God.", strongs: "G2316", original: "θεός" },
    ]
  },
  {
    id: "john-1-2-kjv",
    book: "John",
    chapter: 1,
    verse: 2,
    text: "The same was in the beginning with God.",
    translation: "KJV",
    strongsNumbers: ["G3778", "G2258", "G1722", "G746", "G4314", "G2316"],
    greek: "οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν",
    tokens: [
      { english: "The", strongs: "G3778", original: "" },
      { english: "same", strongs: "G3778", original: "οὗτος" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "in", strongs: "G1722", original: "ἐν" },
      { english: "the", strongs: "G746", original: "" },
      { english: "beginning", strongs: "G746", original: "ἀρχῇ" },
      { english: "with", strongs: "G4314", original: "πρὸς" },
      { english: "God.", strongs: "G2316", original: "θεόν" },
    ]
  },
  {
    id: "john-1-3-kjv",
    book: "John",
    chapter: 1,
    verse: 3,
    text: "All things were made by him; and without him was not any thing made that was made.",
    translation: "KJV",
  },
  {
    id: "john-1-4-kjv",
    book: "John",
    chapter: 1,
    verse: 4,
    text: "In him was life; and the life was the light of men.",
    translation: "KJV",
  },
  {
    id: "john-1-5-kjv",
    book: "John",
    chapter: 1,
    verse: 5,
    text: "And the light shineth in darkness; and the darkness comprehended it not.",
    translation: "KJV",
  },
  {
    id: "john-3-16-kjv",
    book: "John",
    chapter: 3,
    verse: 16,
    text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    translation: "KJV",
  },
  {
    id: "psalm-23-1-kjv",
    book: "Psalms",
    chapter: 23,
    verse: 1,
    text: "The LORD is my shepherd; I shall not want.",
    translation: "KJV",
  },
  {
    id: "psalm-23-2-kjv",
    book: "Psalms",
    chapter: 23,
    verse: 2,
    text: "He maketh me to lie down in green pastures: he leadeth me beside the still waters.",
    translation: "KJV",
  },
];

const esvData: BibleVerseWithTokens[] = [
  {
    id: "john-1-1-esv",
    book: "John",
    chapter: 1,
    verse: 1,
    text: "In the beginning was the Word, and the Word was with God, and the Word was God.",
    translation: "ESV",
    strongsNumbers: ["G1722", "G746", "G2258", "G3056", "G2532", "G3056", "G2258", "G4314", "G2316", "G2532", "G3056", "G2258", "G2316"],
    greek: "Ἐν ἀρχῇ ἦν ὁ λόγος καὶ ὁ λόγος ἦν πρὸς τὸν θεόν καὶ θεὸς ἦν ὁ λόγος",
    tokens: [
      { english: "In", strongs: "G1722", original: "Ἐν" },
      { english: "the", strongs: "G746", original: "" },
      { english: "beginning", strongs: "G746", original: "ἀρχῇ" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "the", strongs: "G3056", original: "ὁ" },
      { english: "Word,", strongs: "G3056", original: "λόγος" },
      { english: "and", strongs: "G2532", original: "καὶ" },
      { english: "the", strongs: "G3056", original: "ὁ" },
      { english: "Word", strongs: "G3056", original: "λόγος" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "with", strongs: "G4314", original: "πρὸς" },
      { english: "God,", strongs: "G2316", original: "θεόν" },
      { english: "and", strongs: "G2532", original: "καὶ" },
      { english: "the", strongs: "G3056", original: "" },
      { english: "Word", strongs: "G3056", original: "λόγος" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "God.", strongs: "G2316", original: "θεός" },
    ]
  },
  {
    id: "john-1-2-esv",
    book: "John",
    chapter: 1,
    verse: 2,
    text: "He was in the beginning with God.",
    translation: "ESV",
    strongsNumbers: ["G3778", "G2258", "G1722", "G746", "G4314", "G2316"],
    greek: "οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν",
    tokens: [
      { english: "He", strongs: "G3778", original: "οὗτος" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "in", strongs: "G1722", original: "ἐν" },
      { english: "the", strongs: "G746", original: "" },
      { english: "beginning", strongs: "G746", original: "ἀρχῇ" },
      { english: "with", strongs: "G4314", original: "πρὸς" },
      { english: "God.", strongs: "G2316", original: "θεόν" },
    ]
  },
  {
    id: "john-1-3-esv",
    book: "John",
    chapter: 1,
    verse: 3,
    text: "All things were made through him, and without him was not any thing made that was made.",
    translation: "ESV",
  },
  {
    id: "john-1-4-esv",
    book: "John",
    chapter: 1,
    verse: 4,
    text: "In him was life, and the life was the light of men.",
    translation: "ESV",
  },
  {
    id: "john-1-5-esv",
    book: "John",
    chapter: 1,
    verse: 5,
    text: "The light shines in the darkness, and the darkness has not overcome it.",
    translation: "ESV",
  },
  {
    id: "john-3-16-esv",
    book: "John",
    chapter: 3,
    verse: 16,
    text: "For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.",
    translation: "ESV",
  },
  {
    id: "psalm-23-1-esv",
    book: "Psalms",
    chapter: 23,
    verse: 1,
    text: "The LORD is my shepherd; I shall not want.",
    translation: "ESV",
  },
  {
    id: "psalm-23-2-esv",
    book: "Psalms",
    chapter: 23,
    verse: 2,
    text: "He makes me lie down in green pastures. He leads me beside still waters.",
    translation: "ESV",
  },
];

const nasbData: BibleVerseWithTokens[] = [
  {
    id: "john-1-1-nasb",
    book: "John",
    chapter: 1,
    verse: 1,
    text: "In the beginning was the Word, and the Word was with God, and the Word was God.",
    translation: "NASB",
    strongsNumbers: ["G1722", "G746", "G2258", "G3056", "G2532", "G3056", "G2258", "G4314", "G2316", "G2532", "G3056", "G2258", "G2316"],
    greek: "Ἐν ἀρχῇ ἦν ὁ λόγος καὶ ὁ λόγος ἦν πρὸς τὸν θεόν καὶ θεὸς ἦν ὁ λόγος",
    tokens: [
      { english: "In", strongs: "G1722", original: "Ἐν" },
      { english: "the", strongs: "G746", original: "" },
      { english: "beginning", strongs: "G746", original: "ἀρχῇ" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "the", strongs: "G3056", original: "ὁ" },
      { english: "Word,", strongs: "G3056", original: "λόγος" },
      { english: "and", strongs: "G2532", original: "καὶ" },
      { english: "the", strongs: "G3056", original: "ὁ" },
      { english: "Word", strongs: "G3056", original: "λόγος" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "with", strongs: "G4314", original: "πρὸς" },
      { english: "God,", strongs: "G2316", original: "θεόν" },
      { english: "and", strongs: "G2532", original: "καὶ" },
      { english: "the", strongs: "G3056", original: "" },
      { english: "Word", strongs: "G3056", original: "λόγος" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "God.", strongs: "G2316", original: "θεός" },
    ]
  },
  {
    id: "john-1-2-nasb",
    book: "John",
    chapter: 1,
    verse: 2,
    text: "He was in the beginning with God.",
    translation: "NASB",
    strongsNumbers: ["G3778", "G2258", "G1722", "G746", "G4314", "G2316"],
    greek: "οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν",
    tokens: [
      { english: "He", strongs: "G3778", original: "οὗτος" },
      { english: "was", strongs: "G2258", original: "ἦν" },
      { english: "in", strongs: "G1722", original: "ἐν" },
      { english: "the", strongs: "G746", original: "" },
      { english: "beginning", strongs: "G746", original: "ἀρχῇ" },
      { english: "with", strongs: "G4314", original: "πρὸς" },
      { english: "God.", strongs: "G2316", original: "θεόν" },
    ]
  },
  {
    id: "john-1-3-nasb",
    book: "John",
    chapter: 1,
    verse: 3,
    text: "All things came into being through Him, and apart from Him nothing came into being that has come into being.",
    translation: "NASB",
  },
  {
    id: "john-1-4-nasb",
    book: "John",
    chapter: 1,
    verse: 4,
    text: "In Him was life, and the life was the Light of men.",
    translation: "NASB",
  },
  {
    id: "john-1-5-nasb",
    book: "John",
    chapter: 1,
    verse: 5,
    text: "The Light shines in the darkness, and the darkness did not comprehend it.",
    translation: "NASB",
  },
  {
    id: "john-3-16-nasb",
    book: "John",
    chapter: 3,
    verse: 16,
    text: "For God so loved the world, that He gave His only begotten Son, that whoever believes in Him shall not perish, but have eternal life.",
    translation: "NASB",
  },
  {
    id: "psalm-23-1-nasb",
    book: "Psalms",
    chapter: 23,
    verse: 1,
    text: "The LORD is my shepherd, I shall not want.",
    translation: "NASB",
  },
  {
    id: "psalm-23-2-nasb",
    book: "Psalms",
    chapter: 23,
    verse: 2,
    text: "He makes me lie down in green pastures; He leads me beside quiet waters.",
    translation: "NASB",
  },
];

// Use complete KJV data with integrated Strong's numbers from kaiserlik/kjv
const kjvData: BibleVerseWithTokens[] = kjvStrongsData as BibleVerseWithTokens[];

const translationData: Record<Translation, BibleVerseWithTokens[]> = {
  KJV: kjvData,
  ESV: esvData,
  NASB: nasbData,
};

export const bibleBooks = [
  // Old Testament
  { name: "Genesis", chapters: 50, testament: "Old" },
  { name: "Exodus", chapters: 40, testament: "Old" },
  { name: "Leviticus", chapters: 27, testament: "Old" },
  { name: "Numbers", chapters: 36, testament: "Old" },
  { name: "Deuteronomy", chapters: 34, testament: "Old" },
  { name: "Joshua", chapters: 24, testament: "Old" },
  { name: "Judges", chapters: 21, testament: "Old" },
  { name: "Ruth", chapters: 4, testament: "Old" },
  { name: "1 Samuel", chapters: 31, testament: "Old" },
  { name: "2 Samuel", chapters: 24, testament: "Old" },
  { name: "1 Kings", chapters: 22, testament: "Old" },
  { name: "2 Kings", chapters: 25, testament: "Old" },
  { name: "1 Chronicles", chapters: 29, testament: "Old" },
  { name: "2 Chronicles", chapters: 36, testament: "Old" },
  { name: "Ezra", chapters: 10, testament: "Old" },
  { name: "Nehemiah", chapters: 13, testament: "Old" },
  { name: "Esther", chapters: 10, testament: "Old" },
  { name: "Job", chapters: 42, testament: "Old" },
  { name: "Psalms", chapters: 150, testament: "Old" },
  { name: "Proverbs", chapters: 31, testament: "Old" },
  { name: "Ecclesiastes", chapters: 12, testament: "Old" },
  { name: "Song of Solomon", chapters: 8, testament: "Old" },
  { name: "Isaiah", chapters: 66, testament: "Old" },
  { name: "Jeremiah", chapters: 52, testament: "Old" },
  { name: "Lamentations", chapters: 5, testament: "Old" },
  { name: "Ezekiel", chapters: 48, testament: "Old" },
  { name: "Daniel", chapters: 12, testament: "Old" },
  { name: "Hosea", chapters: 14, testament: "Old" },
  { name: "Joel", chapters: 3, testament: "Old" },
  { name: "Amos", chapters: 9, testament: "Old" },
  { name: "Obadiah", chapters: 1, testament: "Old" },
  { name: "Jonah", chapters: 4, testament: "Old" },
  { name: "Micah", chapters: 7, testament: "Old" },
  { name: "Nahum", chapters: 3, testament: "Old" },
  { name: "Habakkuk", chapters: 3, testament: "Old" },
  { name: "Zephaniah", chapters: 3, testament: "Old" },
  { name: "Haggai", chapters: 2, testament: "Old" },
  { name: "Zechariah", chapters: 14, testament: "Old" },
  { name: "Malachi", chapters: 4, testament: "Old" },
  // New Testament
  { name: "Matthew", chapters: 28, testament: "New" },
  { name: "Mark", chapters: 16, testament: "New" },
  { name: "Luke", chapters: 24, testament: "New" },
  { name: "John", chapters: 21, testament: "New" },
  { name: "Acts", chapters: 28, testament: "New" },
  { name: "Romans", chapters: 16, testament: "New" },
  { name: "1 Corinthians", chapters: 16, testament: "New" },
  { name: "2 Corinthians", chapters: 13, testament: "New" },
  { name: "Galatians", chapters: 6, testament: "New" },
  { name: "Ephesians", chapters: 6, testament: "New" },
  { name: "Philippians", chapters: 4, testament: "New" },
  { name: "Colossians", chapters: 4, testament: "New" },
  { name: "1 Thessalonians", chapters: 5, testament: "New" },
  { name: "2 Thessalonians", chapters: 3, testament: "New" },
  { name: "1 Timothy", chapters: 6, testament: "New" },
  { name: "2 Timothy", chapters: 4, testament: "New" },
  { name: "Titus", chapters: 3, testament: "New" },
  { name: "Philemon", chapters: 1, testament: "New" },
  { name: "Hebrews", chapters: 13, testament: "New" },
  { name: "James", chapters: 5, testament: "New" },
  { name: "1 Peter", chapters: 5, testament: "New" },
  { name: "2 Peter", chapters: 3, testament: "New" },
  { name: "1 John", chapters: 5, testament: "New" },
  { name: "2 John", chapters: 1, testament: "New" },
  { name: "3 John", chapters: 1, testament: "New" },
  { name: "Jude", chapters: 1, testament: "New" },
  { name: "Revelation", chapters: 22, testament: "New" },
];

export function getVersesByChapter(book: string, chapter: number, translation: Translation = 'KJV'): BibleVerseWithTokens[] {
  return translationData[translation].filter(v => v.book === book && v.chapter === chapter);
}

export const translations: { id: Translation; name: string; fullName: string }[] = [
  { id: 'KJV', name: 'KJV', fullName: 'King James Version' },
  { id: 'ESV', name: 'ESV', fullName: 'English Standard Version' },
  { id: 'NASB', name: 'NASB', fullName: 'New American Standard Bible' },
];
